project:
  type: website

website:
  title: "Phyllosphere microbiome"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Analysis
        menu:
          - href: trial_1.qmd
            text: "Trial 1"
          - href: trial_2.qmd
            text: "Trial 2"
          - href: trial_3.qmd
            text: "Trial 3"
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



