project:
  type: website

website:
  title: "Phyllosphere microbiome"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sources.qmd
      - about.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



